#!/bin/bash
#SBATCH --nodes={nnode}
#SBATCH --ntasks-per-node={taskpernode}
#SBATCH --partition=compute
#SBATCH -t 48:00:00
#SBATCH --output=output
#SBATCH --error=error
#SBATCH --export=ALL=

module load vasp
mpirun -np {ntask} vasp_gam
