#!/bin/bash
#SBATCH --nodes={nnode}
#SBATCH --ntasks-per-node={taskpernode}
#SBATCH --partition=compute
#SBATCH -t 48:00:00
#SBATCH --output=output
#SBATCH --error=error
#SBATCH --export=ALL

date
module load vasp/5.4.4  # XSEDE ticket #134504: vasp 6 not on all nodes
mpirun -np {ntask} vasp_gam
date
