#!/bin/bash
#SBATCH -N {nnode}
#SBATCH -C haswell
#SBATCH -q regular
#SBATCH -t 48:00:00
#SBATCH -o output
#SBATCH -e error

module load vasp

cp INCAR1 INCAR
date
srun -n{ntask} -c2 --cpu_bind=cores vasp_gam
date

cp CONTCAR CONTCAR1
cp CONTCAR POSCAR
cp INCAR2 INCAR
date
srun -n{ntask} -c2 --cpu_bind=cores vasp_gam
date
